# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LandingWindow\Interfaces\LandingWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys

from AddProfileWindow import *
from EntryWindow import *
from ReportWindow import *


class Ui_LandingWindow(object):
    def setupUi(self, LandingWindow):
        LandingWindow.setObjectName("LandingWindow")
        LandingWindow.resize(1000, 650)
        LandingWindow.setAutoFillBackground(False)
        LandingWindow.setStyleSheet("#LandingWindow{background-color: rgb(226, 255, 250)}")
        self.centralwidget = QtWidgets.QWidget(LandingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.report = QtWidgets.QPushButton(self.centralwidget)
        self.report.setEnabled(True)
        self.report.setGeometry(QtCore.QRect(50, 330, 200, 200))
        self.report.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.report.setAutoFillBackground(False)
        self.report.setStyleSheet("border-style: solid;\n"
                                  "border-radius:500px;\n"
                                  "border-color: red;\n"
                                  "max-width:200px;\n"
                                  "max-height:200px;\n"
                                  "min-width:200px;\n"
                                  "min-height:200px;")
        self.report.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/report.png"), QtGui.QIcon.Normal,
                       QtGui.QIcon.Off)
        self.report.setIcon(icon)
        self.report.setIconSize(QtCore.QSize(200, 200))
        self.report.setAutoDefault(False)
        self.report.setDefault(False)
        self.report.setFlat(True)
        self.report.setObjectName("report")
        self.make_entry = QtWidgets.QPushButton(self.centralwidget)
        self.make_entry.setGeometry(QtCore.QRect(280, 330, 200, 200))
        self.make_entry.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.make_entry.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/add.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.make_entry.setIcon(icon1)
        self.make_entry.setIconSize(QtCore.QSize(215, 215))
        self.make_entry.setAutoDefault(False)
        self.make_entry.setDefault(False)
        self.make_entry.setFlat(False)
        self.make_entry.setObjectName("make_entry")
        self.backup = QtWidgets.QPushButton(self.centralwidget)
        self.backup.setGeometry(QtCore.QRect(510, 330, 200, 200))
        self.backup.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.backup.setAutoFillBackground(False)
        self.backup.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/backup.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.backup.setIcon(icon2)
        self.backup.setIconSize(QtCore.QSize(200, 200))
        self.backup.setAutoDefault(False)
        self.backup.setDefault(False)
        self.backup.setFlat(False)
        self.backup.setObjectName("backup")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(740, 330, 200, 200))
        self.exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exit.setStyleSheet("border-style: solid;\n"
                                "border-radius:500px;\n"
                                "border-color: red;\n"
                                "max-width:200px;\n"
                                "max-height:200px;\n"
                                "min-width:200px;\n"
                                "min-height:200px;")
        self.exit.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/exit.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.exit.setIcon(icon3)
        self.exit.setIconSize(QtCore.QSize(200, 200))
        self.exit.setAutoDefault(False)
        self.exit.setDefault(False)
        self.exit.setFlat(False)
        self.exit.setObjectName("exit")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(245, 60, 500, 121))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap("assets/vedanya_logo.png"))
        self.logo_label.setScaledContents(False)
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(250, 180, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic Light")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignBottom | QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        LandingWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LandingWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 25))
        self.menubar.setObjectName("menubar")
        self.menuVedanya = QtWidgets.QMenu(self.menubar)
        self.menuVedanya.setObjectName("menuVedanya")
        LandingWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LandingWindow)
        self.statusbar.setObjectName("statusbar")
        LandingWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(LandingWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(LandingWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSupport = QtWidgets.QAction(LandingWindow)
        self.actionSupport.setObjectName("actionSupport")
        self.menuVedanya.addAction(self.actionSupport)
        self.menuVedanya.addAction(self.actionAbout)
        self.menuVedanya.addAction(self.actionExit)
        self.menubar.addAction(self.menuVedanya.menuAction())

        self.report.clicked.connect(self.launchReportWindow)
        self.make_entry.clicked.connect(self.launchEntryWindow)
        self.exit.clicked.connect(exitProgram)

        self.retranslateUi(LandingWindow)
        QtCore.QMetaObject.connectSlotsByName(LandingWindow)

    def retranslateUi(self, LandingWindow):
        _translate = QtCore.QCoreApplication.translate
        LandingWindow.setWindowTitle(_translate("LandingWindow", "MainWindow"))
        self.make_entry.setStyleSheet(_translate("LandingWindow", "border-style: solid;\n"
                                                                  "border-radius:500px;\n"
                                                                  "border-color: red;\n"
                                                                  "max-width:200px;\n"
                                                                  "max-height:200px;\n"
                                                                  "min-width:200px;\n"
                                                                  "min-height:200px;"))
        self.backup.setStyleSheet(_translate("LandingWindow", "border-style: solid;\n"
                                                              "border-radius:500px;\n"
                                                              "border-color: red;\n"
                                                              "max-width:200px;\n"
                                                              "max-height:200px;\n"
                                                              "min-width:200px;\n"
                                                              "min-height:200px;"))
        self.label.setText(_translate("LandingWindow", "FINANCIAL RESOURCE MANAGEMENT"))
        self.menuVedanya.setTitle(_translate("LandingWindow", "Vedanya"))
        self.actionExit.setText(_translate("LandingWindow", "Exit"))
        self.actionAbout.setText(_translate("LandingWindow", "About"))
        self.actionSupport.setText(_translate("LandingWindow", "Support"))

    def launchReportWindow(self):
        self.reportWindow = QtWidgets.QMainWindow()
        self.reportWindowUi = Ui_ReportsWindow()
        self.reportWindowUi.setupUi(self.reportWindow)
        self.reportWindow.show()

    def launchEntryWindow(self):
        self.entryWindow = QtWidgets.QMainWindow()
        self.entryWindowUi = Ui_EntryWindow()
        self.entryWindowUi.setupUi(self.entryWindow)
        self.entryWindow.show()

    def launchBackupWindow(self):
        pass


app = QtWidgets.QApplication(sys.argv)


def exitProgram():
    sys.exit(app.exec_())


if __name__ == "__main__":
    import sys

    LandingWindow = QtWidgets.QMainWindow()
    ui = Ui_LandingWindow()
    ui.setupUi(LandingWindow)
    LandingWindow.show()
    sys.exit(app.exec_())
